title: Blog für Bibliotheks- und Archivinformatik
author: Simone
email: simone.behrschneider@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch für das Modul Bibliotheks- und Archivinformatik HS2021

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
